### ISSUE TITLE
How do I get to this area?

### ISSUE THREAD

**Issue by Griffork** [c-ostic/OriBFArchipelago#75]
I'm wondering what I'm not understanding on how to get to Bash. I've just changed the logic difficulty from "casual" to "normal". I'm playing on my own.

It seems like I need to already have Bash to get into Horu Fields to get Bash?

This is path that the spoiler log generates:

```
HoruFieldsHiddenExp
        Menu -> Menu -> SunkenGladesRunaway
   =>   SunkenGladesRunaway -> SunkenGladesRunaway_to_TeleporterNetwork_5
   =>   TeleporterNetwork -> TeleporterNetwork_to_MoonGrotto_3
   =>   MoonGrotto -> MoonGrotto_to_MoonGrottoAboveTeleporter_2
   =>   MoonGrottoAboveTeleporter -> MoonGrottoAboveTeleporter_to_UpperGrotto_1
   =>   UpperGrotto -> UpperGrotto_to_Iceless_4
   =>   Iceless -> Iceless_to_HollowGrove_1
   =>   HollowGrove -> HollowGrove_to_HoruFields_4
   =>   HoruFields -> HoruFields_to_HoruFieldsPushBlock_1
   =>   HoruFieldsPushBlock
```

My understanding is that Iceless is the map stone that's half-way between the HoruTP and ThornfeltTP (in the area with all the giant dead trees and blue jump flowers).

I believe this says I'm supposed to go left into HoruFields_4, which is the place with the green explody rolly-pollies that I'm supposed to use to break open the walls to continue into Horu Fields. I've tried using Stomp and ChargeJump to push them around but it doesn't work - seems I need Bash to do this?

<hr/>

This is my spoiler log's spheres:

```
Playthrough:

0: {

}
1: {
  FirstEnergyCell: EnergyCell
  FirstPickup: GladesKeyStone
  FronkeyFight: GladesKeyStone
}
2: {
  GladesMapKeystone: TPGrotto
  LeftGladesHiddenExp: Wind
  WallJumpSkillTree: WarmthFragment
}
3: {
  GrottoHideoutFallAbilityCell: WallJump
  GumoHideoutLeftHangingExp: EnergyCell
}
4: {
  DashAreaRoofExp: DoubleJump
  DashSkillTree: WarmthFragment
  DeathGauntletExp: WarmthFragment
  GumoHideoutMiniboss: WarmthFragment
}
5: {
  AboveFourthHealth: WarmthFragment
  FarLeftGumoHideoutExp: WarmthFragment
  GrottoLasersRoofExp: ChargeJump
  GumoHideoutRightHangingExp: CleanWater
  HollowGroveTreeAbilityCell: EnergyCell
  LeftGumoHideoutHealthCell: EnergyCell
}
6: {
  GladesLaser: Dash
  GladesMainPoolDeep: WarmthFragment
  GroveAboveSpiderWaterHealthCell: WarmthFragment
  GumoHideoutRedirectExp: WarmthFragment
  LeftGumoHideoutSwim: Stomp
  SpiritCavernsTopRightKeystone: WarmthFragment
  SwampEntranceSwim: Glide
  WallJumpAreaExp: WarmthFragment
}
7: {
  HoruFieldsHiddenExp: Bash
  LowerBlackrootLaserExp: WarmthFragment
  ValleyRightSwimExp: WarmthFragment
}
```

This is my config file:

```
name: Name
game: Ori and the Blind Forest
requires:
  version: 0.5.1

Ori and the Blind Forest:
  progression_balancing:
    45: 50

  accessibility:
    full: 50
    minimal: 0

  goal:
    all_skill_trees: 0
    all_maps: 0
    warmth_fragments: 50
    world_tour: 0
    none: 0

  warmth_fragments_available:
    40: 50
    random: 0
    random-low: 0
    random-high: 0

  warmth_fragments_required:
    30: 50
    random: 0
    random-low: 0
    random-high: 0

  logic_difficulty:
    casual: 0
    standard: 50
    expert: 0
    master: 0
    glitched: 0

  keystone_logic:
    anywhere: 0
    area_specific: 50

  mapstone_logic:
    anywhere: 50
    area_specific: 0
    progressive: 0

  extra_mapstones:
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  deathlink_logic:
    disabled: 0
    partial: 50
    full: 0

  enable_lure:
    'false': 0
    'true': 50

  enable_damage_boost:
    'false': 50
    'true': 0

  enable_double_bash:
    'false': 0
    'true': 50

  enable_grenade_jump:
    'false': 50
    'true': 0

  enable_air_dash:
    'false': 50
    'true': 0

  enable_charge_dash:
    'false': 50
    'true': 0

  enable_triple_jump:
    'false': 50
    'true': 0

  enable_charge_flame_burn:
    'false': 50
    'true': 0

  enable_rekindle:
    'false': 50
    'true': 0

  restrict_dungeon_keys:
    'false': 0
    'true': 50

  local_items: []
  non_local_items: []
  start_inventory: {}
  start_hints: []
  start_location_hints: []
  exclude_locations: []
  priority_locations: []
  item_links: []
```
